services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  node_modules:
